# fly.toml app configuration file generated for boalix-sync on 2026-06-03T19:27:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boalix-sync'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/boalix-sync.db'
  PORT = '8080'
  RUST_LOG = 'boalix_sync_server=info,warn'

[[mounts]]
  source = 'boalix_sync_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
